/**
 * server.mocks.ts
 * Realistic mock responses for every Gemini-backed endpoint.
 * Used when DEV_MOCK=true in .env to avoid burning API quota during local dev.
 */

export const DEV_MOCKS: Record<string, any> = {
  radar: {
    week: 'Apr 7–13, 2026',
    topTrends: [
      {
        title: 'Agentic AI Infrastructure Boom',
        description:
          'OpenAI, Google, and Anthropic all shipped agentic frameworks this week. Enterprise demand for "agent governance" tooling is spiking 340% on Google Trends.',
        impact: 'High',
        sector: 'AI/SaaS',
      },
      {
        title: 'EU AI Act Wave 2 Enforcement',
        description:
          'EU AI Act enforcement begins Q2 2026. 65% of mid-market EU companies are non-compliant. Compliance tooling vendors report a 5× inbound spike.',
        impact: 'High',
        sector: 'RegTech',
      },
      {
        title: 'Embedded Finance Consolidation Window',
        description:
          'Stripe, Adyen, and Marqeta are acquiring smaller embedded finance players. White-label fintech infrastructure has a 12-month window before market consolidates.',
        impact: 'Medium',
        sector: 'FinTech',
      },
      {
        title: 'SEC Climate Disclosure Rules Take Effect',
        description:
          'Mandatory ESG reporting kicks in for large accelerated filers in 2026. 80% of S&P 500 CFOs cite sustainability reporting as their top operational pain point.',
        impact: 'Medium',
        sector: 'Climate/Sustainability',
      },
      {
        title: 'Healthcare AI Prior Authorization Disruption',
        description:
          'CMS guidance allows AI to automate prior auth decisions. 300M+ annual prior auth requests represent a $13B administrative cost opportunity.',
        impact: 'High',
        sector: 'HealthTech',
      },
    ],
    marketShift:
      'The center of gravity in B2B SaaS is shifting from "software that helps humans work" to "software that works autonomously." Buyers are now evaluating on agent-readiness, not feature parity. Winners will be AI-native products with proprietary data loops — not wrappers.',
    opportunityAreas: [
      'Agent orchestration and observability tooling for enterprise workflows',
      'Automated ESG/climate reporting infrastructure for mid-market',
      'Prior authorization automation for specialty healthcare providers',
      'EU AI Act compliance auditing for non-EU companies selling into Europe',
      'Embedded finance infrastructure for creator economy platforms',
    ],
  },

  futurecasting: {
    horizon: '2030',
    predictions: [
      {
        title: '90% of B2B software development is AI-generated',
        probability: 0.78,
        rationale:
          'Current trajectory of AI coding tools (Cursor, Devin, Claude Code) suggests most CRUD apps will be auto-generated by 2030. Software becomes a commodity; data and distribution remain the moat.',
        winners: [
          'Companies with proprietary datasets',
          'Orchestration layer providers',
          'Domain experts who can specify requirements precisely',
        ],
        losers: [
          'Commodity software development agencies',
          'Early-career developers without AI fluency',
          'SaaS companies competing purely on features',
        ],
      },
      {
        title: 'Physical-digital convergence makes location-independent work the default',
        probability: 0.65,
        rationale:
          'Spatial computing + AI translation + async-first tools will make synchronous, collocated work optional for knowledge workers by 2030.',
        winners: [
          'Remote-first companies with global talent pipelines',
          'Spatial computing platform developers',
          'Async productivity tool vendors',
        ],
        losers: [
          'Commercial real estate in tier-1 cities',
          'Business travel industry',
          'Traditional office productivity suites',
        ],
      },
      {
        title: 'Personalized AI agents handle 40% of consumer financial decisions',
        probability: 0.58,
        rationale:
          'As trust in AI advisors grows and regulation adapts, consumers will delegate routine decisions (insurance comparison, bill negotiation, investment rebalancing) to agents.',
        winners: [
          'Agent-native fintech platforms',
          'Open banking infrastructure providers',
          'Behavioral finance AI companies',
        ],
        losers: [
          'Traditional financial advisors serving mass market',
          'Legacy banking apps with manual UX',
          'Insurance brokers without AI integration',
        ],
      },
    ],
    paradigmShifts: [
      'From "software subscriptions" to "outcome contracts" — AI agents get paid per result, not per seat',
      'From "companies hire employees" to "projects attract contributors" — gig-first, equity-second economy',
      'From "data privacy" to "data sovereignty" — individuals monetize their own data via personal data vaults',
    ],
  },

  'action-plan': {
    roadmap: [
      {
        id: 'step-1',
        step: 'Run 20 ICP discovery interviews',
        details:
          'Identify 20 target customers via LinkedIn, cold email, or warm intros. Ask about pain severity and current workarounds. Aim for 45-minute conversations.',
        milestone: '10+ confirmed pain points documented',
      },
      {
        id: 'step-2',
        step: 'Build a no-code MVP in 2 weeks',
        details:
          'Use Bubble, Glide, or Webflow to ship a functional prototype. Focus exclusively on the core value loop — resist feature creep.',
        milestone: 'Working prototype with 3 core features live',
      },
      {
        id: 'step-3',
        step: 'Recruit first 10 beta users',
        details:
          'Leverage your network, relevant Slack/Discord communities, and a ProductHunt upcoming page.',
        milestone: '10 weekly active beta users',
      },
      {
        id: 'step-4',
        step: 'Charge from day one',
        details:
          'Introduce a $49/mo pricing tier immediately. Even $490 MRR from 10 users validates willingness to pay.',
        milestone: '$490 MRR',
      },
      {
        id: 'step-5',
        step: 'Apply to YC or a vertical accelerator',
        details:
          'With early traction and a clear thesis, apply to YC, Techstars, or a sector-specific accelerator.',
        milestone: 'Application submitted',
      },
      {
        id: 'step-6',
        step: 'Hire first technical co-founder or contractor',
        details:
          'Use Contra, Toptal, or AngelList Talent. Prioritize someone who has shipped production SaaS before.',
        milestone: 'First technical hire onboarded',
      },
      {
        id: 'step-7',
        step: 'Launch publicly on ProductHunt',
        details:
          'Prepare assets, recruit a well-connected hunter, and schedule launch for Tuesday–Thursday for maximum visibility.',
        milestone: 'Top 5 Product of the Day',
      },
    ],
    tools: [
      'Bubble (no-code MVP)',
      'Notion (documentation)',
      'Stripe (payments)',
      'Loom (async demos)',
      'Linear (task management)',
      'Figma (design)',
      'Intercom (customer support)',
    ],
    risks: [
      'Market may be too niche to hit venture scale',
      'Incumbents can copy quickly once traction is visible',
      'Regulatory constraints in key target markets',
      'Customer acquisition cost may exceed lifetime value at early pricing',
    ],
    timeline: '12 weeks to first 10 paying customers',
  },

  'build-me': {
    promptPack: [
      {
        title: 'Landing Page Copy',
        prompt:
          'Write high-converting landing page copy for this idea. Include: a punchy hero headline (under 8 words), subheadline (under 20 words), 3 benefit-focused value props, a FAQ section with 5 questions, and a strong CTA. Tone: confident, founder-to-founder. No hype, no buzzwords.',
      },
      {
        title: 'Cold Email Sequence (3-email)',
        prompt:
          'Write a 3-email cold outreach sequence for this idea targeting [ICP]. Email 1: pattern interrupt (insight-led). Email 2: follow-up with social proof. Email 3: breakup email. Subject lines under 50 chars. Each email under 120 words. No pitching in email 1.',
      },
      {
        title: 'System Architecture Blueprint',
        prompt:
          'Design a production-ready system architecture. Include: recommended tech stack (frontend, backend, database, auth, infra), core API routes with HTTP methods, database schema for the 3 primary entities, and 2 scaling bottlenecks to watch for. Output as structured markdown.',
      },
      {
        title: '10-Slide Pitch Deck Outline',
        prompt:
          'Create a 10-slide pitch deck outline following the YC format: Problem, Solution, Market Size (TAM/SAM/SOM), Product (with demo flow), Traction, Team, Business Model, Competition (2×2 matrix), Roadmap, and Ask (raise amount + use of funds). One key message per slide.',
      },
      {
        title: 'MVP Feature Prioritization (ICE)',
        prompt:
          'List exactly 3 features for v1.0, 3 for v1.1, and 3 for v2.0. For each feature, provide: feature name, user story (as a [user] I want [action] so that [benefit]), and ICE score (Impact 1-10, Confidence 1-10, Ease 1-10). Sort by ICE score within each version.',
      },
    ],
    repoStructure:
      'src/\n  components/\n    ui/          # shadcn/ui primitives\n    features/    # domain feature components\n  hooks/         # custom React hooks\n  services/\n    api.ts       # BFF client\n    auth.ts      # Firebase auth helpers\n  utils/\n  types/\nserver/\n  routes/        # Express route handlers\n  middleware/    # auth, rate-limit, validation\n  models/        # Firestore data models\npublic/\n.env.example\nREADME.md\npackage.json',
    first24Hours: [
      'Create GitHub repo, set up CI/CD (GitHub Actions → Vercel), configure branch protection on main',
      'Register domain ($12) and stand up a Typedream or Framer landing page with a waitlist form (Tally.so)',
      'Post in 3 relevant communities (Reddit, relevant Slack/Discord) to gauge interest and collect emails',
      'Open Figma and create a design system file with brand tokens (2 colors, 1 typeface, 8px spacing grid)',
      'Book 5 discovery calls with potential users for this week using Calendly',
    ],
  },

  validation: {
    landingPage: {
      hero: 'Stop guessing. Start building what the market actually wants.',
      subHero:
        'Join 500+ founders who validated their idea in 48 hours — before writing a single line of code.',
      valueProps: [
        'Save 80% of validation time with structured ICP interviewing frameworks',
        'Turn raw customer feedback into investor-ready traction metrics automatically',
        'Ship a smoke test in under 2 hours with our pre-built landing page templates',
      ],
    },
    interviewScript: [
      'Walk me through the last time you ran into [core problem]. What happened?',
      'How are you currently solving this? What tools, workarounds, or people do you use?',
      'What is the single most painful part of your current solution?',
      'If you could wave a magic wand and fix this overnight, what would that look like?',
      'How much are you currently spending on solving this — in time and in money — per month?',
      'Who else on your team or in your organization is affected by this problem?',
      'On a scale of 1–10, how urgent is it for you to solve this right now? What would make it a 10?',
    ],
    smokeTest:
      'Build a 5-question Typeform with a $49 pre-order button at the end. Drive 500 visitors over 7 days via targeted Reddit posts, a Hacker News "Show HN", and 3 relevant newsletter sponsor slots. Target: 15+ pre-orders (3% conversion) to confirm paid demand before investing in development.',
    successMetrics: [
      '20+ ICP interviews completed with 80%+ citing strong, active pain',
      '3%+ conversion rate on the smoke test landing page',
      '5 paying beta customers at any price point within 30 days of launch',
      'NPS of 40+ from the first cohort of 20 beta users',
      'Average weekly active usage > 2× per user per week after 4 weeks',
    ],
  },

  vetting: {
    score: 7.8,
    verdict: 'High Conviction',
    strengths: [
      'Strong regulatory tailwind — new compliance mandates create forced adoption with little sales resistance',
      'B2B SaaS model delivers predictable recurring revenue with high switching costs once integrated',
      'AI-native data moat: the product gets measurably better with each customer added to the training loop',
    ],
    weaknesses: [
      'Enterprise sales cycles are 3–6 months — burn rate risk without bridge capital',
      'Requires deep domain expertise that is difficult and expensive to hire for at seed stage',
      'Incumbent players have established relationships and can bundle a "good enough" competitive feature',
    ],
    pivotSuggestions: [
      'Start with the mid-market (50–500 employees) to compress sales cycles from months to weeks',
      'Launch a free compliance audit tool to build top-of-funnel brand and a proprietary data moat simultaneously',
      'Consider a marketplace model connecting compliance officers directly with audited vendors',
    ],
    comparableExits: [
      'OneTrust — acquired at $9.7B valuation (privacy compliance SaaS, 2023)',
      'Drata — raised $200M at $2B valuation (compliance automation, Series C)',
      'Vanta — reached $1.6B valuation at Series B (SOC 2 automation, 2022)',
    ],
  },

  explain: {
    text: 'This step is critical because it de-risks the entire venture before you invest significant capital. The core insight is to separate real signal from wishful thinking — most founders skip this phase and build on assumptions. By completing 20 ICP interviews in the first 2 weeks, you establish a baseline of authentic customer language that you can use directly in your landing page copy, pitch deck, and sales emails. The milestone is deliberately set at "10+ confirmed pain points" rather than just "interviews completed" — because you want quality signal, not volume. If you cannot find 10 people describing the same pain independently, that is valuable data telling you to pivot before you write a line of code.',
  },
};

/**
 * Returns mock data for a given feature type, optionally personalised with idea data.
 */
export function getMockResponse(featureType: string, idea?: { headline?: string }): any {
  const base = DEV_MOCKS[featureType];
  if (!base) return null;

  // Personalise action-plan and build-me with the actual idea headline
  if (idea?.headline && (featureType === 'action-plan' || featureType === 'build-me')) {
    if (featureType === 'action-plan') {
      return {
        ...base,
        roadmap: base.roadmap.map((step: any, i: number) => ({
          ...step,
          step: i === 0 ? `Validate "${idea.headline}" with 20 ICP interviews` : step.step,
        })),
      };
    }
  }

  if (idea?.headline && featureType === 'explain') {
    return { text: `For "${idea.headline}": ${base.text}` };
  }

  return base;
}
