import { Idea } from '../types';
import { jsPDF } from 'jspdf';

export const exportToPDF = (idea: Idea, format: string) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > 280) {
      doc.addPage();
      y = 20;
    }
  };

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(idea.headline.toUpperCase(), margin, y);
  y += 12;

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(100);
  doc.text(`TAGS: ${(idea.categoryTags || []).join(', ')}`, margin, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(50);
  const pitchLines = doc.splitTextToSize(`"${idea.pitch}"`, 170);
  doc.text(pitchLines, margin, y);
  y += pitchLines.length * 6 + 10;

  doc.setDrawColor(200);
  doc.line(margin, y, 190, y);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text("VC ANALYSIS", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  const vcLines = doc.splitTextToSize(idea.vcJustification, 170);
  doc.text(vcLines, margin, y);
  y += vcLines.length * 5 + 10;

  checkPage(30);
  doc.setFont("helvetica", "bold");
  doc.text("REVENUE MODEL", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  const revLines = doc.splitTextToSize(idea.revenueSkeleton, 170);
  doc.text(revLines, margin, y);
  y += revLines.length * 5 + 10;

  if (idea.fullActionPlan) {
    checkPage(30);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text("EXECUTION ROADMAP", margin, y);
    y += 10;
    doc.setTextColor(0);

    idea.fullActionPlan.roadmap.forEach((step, i) => {
      checkPage(25);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`${i + 1}. ${step.step}`, margin, y);
      y += 6;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      const stepLines = doc.splitTextToSize(step.details, 160);
      doc.text(stepLines, margin + 5, y);
      y += stepLines.length * 5 + 2;
      doc.setTextColor(150);
      doc.text(`Milestone: ${step.milestone}`, margin + 5, y);
      y += 8;
      doc.setTextColor(0);
    });
  }

  if (idea.validationToolkit) {
    doc.addPage();
    y = 20;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text("VALIDATION TOOLKIT", margin, y);
    y += 10;
    doc.setTextColor(0);

    doc.setFontSize(12);
    doc.text("LANDING PAGE COPY", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.text(`Hero: ${idea.validationToolkit.landingPage.hero}`, margin + 5, y);
    y += 6;
    doc.text(`Sub-hero: ${idea.validationToolkit.landingPage.subHero}`, margin + 5, y);
    y += 6;
    doc.text("Value Props:", margin + 5, y);
    y += 6;
    idea.validationToolkit.landingPage.valueProps.forEach(vp => {
      doc.text(`- ${vp}`, margin + 10, y);
      y += 6;
    });
    y += 4;

    checkPage(30);
    doc.setFont("helvetica", "bold");
    doc.text("CUSTOMER INTERVIEW QUESTIONS", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    idea.validationToolkit.interviewScript.forEach((q, i) => {
      checkPage(15);
      const qLines = doc.splitTextToSize(`${i + 1}. ${q}`, 160);
      doc.text(qLines, margin + 5, y);
      y += qLines.length * 6 + 2;
    });
  }

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text(`Generated by Trend-Equity on ${new Date().toLocaleDateString()}`, margin, 280);

  doc.save(`${idea.headline.replace(/\s+/g, '_')}_Full_Plan.pdf`);
};

export const exportListToCSV = (ideas: Idea[], activeTab: string, today: string) => {
  if (ideas.length === 0) {
    alert("No ideas to export.");
    return;
  }

  const headers = ["Idea Name", "Tags", "Description"];
  const rows = ideas.map(idea => [
    `"${idea.headline.replace(/"/g, '""')}"`,
    `"${(idea.categoryTags || []).join(', ').replace(/"/g, '""')}"`,
    `"${idea.pitch.replace(/"/g, '""')}"`
  ]);

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `Trend_Equity_Ideas_${activeTab}_${today}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const exportListToPDF = (ideas: Idea[], activeTab: string, today: string) => {
  if (ideas.length === 0) {
    alert("No ideas to export.");
    return;
  }

  const doc = new jsPDF();
  const margin = 20;
  let y = 20;
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(`TREND EQUITY: ${activeTab.toUpperCase()} IDEAS`, margin, y);
  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, margin, y);
  y += 15;

  ideas.forEach((idea, index) => {
    if (y > pageHeight - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(16, 185, 129);
    doc.text(`${index + 1}. ${idea.headline.toUpperCase()}`, margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100);
    doc.text(`TAGS: ${(idea.categoryTags || []).join(', ')}`, margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    const pitchLines = doc.splitTextToSize(idea.pitch, 170);
    doc.text(pitchLines, margin, y);
    y += pitchLines.length * 5 + 10;
  });

  doc.save(`Trend_Equity_Ideas_${activeTab}_${today}.pdf`);
};
